spring:
  cloud:
    gateway:
      routes:
        - id : patient-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/patient/**
        - id: medecin-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/medecin/**

  application:
    name: gateway-service
server:
  port: 8888